// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCIX7nzKGDfYX-doFliNXaWG_WCzg7fAM',
    appId: '1:156600665362:web:2334b68faea64f8a581fcb',
    messagingSenderId: '156600665362',
    projectId: 'learningapp-89c0f',
    authDomain: 'learningapp-89c0f.firebaseapp.com',
    storageBucket: 'learningapp-89c0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7qI4OjHheAREfPmvVrTkmf44KL1XvcK4',
    appId: '1:156600665362:android:1d0748a6b2d0ee7b581fcb',
    messagingSenderId: '156600665362',
    projectId: 'learningapp-89c0f',
    storageBucket: 'learningapp-89c0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB92Mt8UYu45W6qrtulN1mSrlOHlURgTmE',
    appId: '1:156600665362:ios:64792247cd63b6b1581fcb',
    messagingSenderId: '156600665362',
    projectId: 'learningapp-89c0f',
    storageBucket: 'learningapp-89c0f.appspot.com',
    iosBundleId: 'com.example.learningapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB92Mt8UYu45W6qrtulN1mSrlOHlURgTmE',
    appId: '1:156600665362:ios:2f9cedd0db3f2bf7581fcb',
    messagingSenderId: '156600665362',
    projectId: 'learningapp-89c0f',
    storageBucket: 'learningapp-89c0f.appspot.com',
    iosBundleId: 'com.example.learningapp.RunnerTests',
  );
}
